name: AkariCommandEnhance
main: org.owari.akari.enhance.Main
version: 1.0.0
api-version: 1.12
author: Mochizuki Haruka
description: the most powerful minecraft command enhance plugin
depend: [PlaceholderAPI]
